dayzoffer/accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import login_user, user_registration, log_out, vender_registration, vendor_login

urlpatterns = [
    url(r'^signin/$', login_user, name="signin"),
    url(r'^vendor_login/$', vendor_login, name="vendor_login"),
    url(r'^register/$', user_registration, name="register"),
    url(r'^logout/$', log_out, name="logout"),
    url(r'^seller_register/$', vender_registration, name="seller-register"),
]

dayzoffer/dayzoffer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from offers.views import HomeListView, newsletter

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^vendor/', include('vendor.urls', namespace='vendor')),
    url(r'^offers/', include('offers.urls', namespace='offers')),
    url(r'^$', HomeListView.as_view(), name="home"),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^newsletter/$', newsletter, name="newsletter"),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Dayzoffer'

dayzoffer/offers/urls.py
from django.conf.urls import url
from .views import OfferDetailView, CategoryDetailView

urlpatterns = [
    url(r'^(?P<slug>[-\w]+)/$', CategoryDetailView.as_view(), name='category-detail'),
    url(r'^offer/(?P<slug>[-\w]+)/$', OfferDetailView.as_view(), name="offer-detail"),
]

dayzoffer/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">


<!-- Mirrored from mamoot-themes.com/theme-preview/z-theme-1-2/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 27 Mar 2016 05:54:21 GMT -->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Dayzoffer.com</title>
  <link rel="icon" href="{% static 'assets/images/favicon.ico' %}">
  <script src="{% static 'assets/js/page/carousel-preload.js' %}"></script>

  <!--[if IE 8]><html class="ie8"><![endif]-->
  <!-- Bootstrap -->
  <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Fonts -->
  <!-- <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,600,700,800,300' rel='stylesheet' type='text/css'> -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Plugins -->
  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/magnific-popup.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/owl.carousel.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/owl.theme.css' %}">
  <!-- Theme -->
  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/carousel-animate.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/theme.css' %}" id="color-style">
  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/custom.css' %}" id="color-style">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!-- [if lt IE 9]> -->
      <!-- <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script> -->
  <!-- <![endif] -->
  {% block style %}
  {% endblock style %}
</head>

<body class="body-nav-fixed-menu-top">
  <div class="wrapper-body">

    <!-- NAVBAR -->
    <!--===============================================================-->
    {% include "header.html" %}
    <!-- NAVBAR END -->

    <!-- SECTION INTRO SLIDER -->
    <!--===============================================================-->
    {% if messages %}
          <div class="container">
              {% for message in messages %}             
                <div class='alert alert-{% if message.tags == "success" %}success{% else %}danger{% endif %} text-center alert-dismissible'>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                </div>          
              {% endfor %}
           
          </div>
    {% endif %}
    {% block content %}

    {% endblock content %}

    <!-- SECTION FOOTER -->
    <!--===============================================================-->
    {% include "footer.html" %}
  </div>
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <!-- <script src="//code.jquery.com/jquery-1.12.0.min.js"></script> -->
  <script src="{% static 'assets/js/jquery.min.js' %}"></script>
  <script src="{% static 'assets/js/page/page.navbar-fixed-shrinked.js' %}"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/owl.carousel.js' %}"></script>
  <script src="{% static 'assets/js/jquery.magnific-popup.js' %}"></script>
  <script src="{% static 'assets/js/jquery.waypoints.js' %}"></script>
  <script src="{% static 'assets/js/jquery.countTo.js' %}"></script>
  <script src="{% static 'assets/js/jquery.bxslider.js' %}"></script>
  <script src="{% static 'assets/js/page/theme.js' %}"></script>
  <script src="{% static 'assets/js/page/page.shop-sidebar-and-item.js' %}"></script>
  <script src="{% static 'assets/js/page/page.home.js' %}"></script>
  <script src="{% static 'assets/js/custom.js' %}"></script>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-59515546-1', 'auto');
    ga('send', 'pageview');

  </script>
<script>
  $(document).ready(function(){
    {% block jquery %}
      
    {% endblock jquery %}
  });
</script>
<script type="text/javascript">/* <![CDATA[ */(function(d,s,a,i,j,r,l,m,t){try{l=d.getElementsByTagName('a');t=d.createElement('textarea');for(i=0;l.length-i;i++){try{a=l[i].href;s=a.indexOf('/cdn-cgi/l/email-protection');m=a.length;if(a&&s>-1&&m>28){j=28+s;s='';if(j<m){r='0x'+a.substr(j,2)|0;for(j+=2;j<m&&a.charAt(j)!='X';j+=2)s+='%'+('0'+('0x'+a.substr(j,2)^r).toString(16)).slice(-2);j++;s=decodeURIComponent(s)+a.substr(j,m-j)}t.innerHTML=s.replace(/</g,'&lt;').replace(/>/g,'&gt;');l[i].href='mailto:'+t.value}}catch(e){}}}catch(e){}})(document);/* ]]> */</script></body>


<!-- Mirrored from mamoot-themes.com/theme-preview/z-theme-1-2/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 27 Mar 2016 05:55:09 GMT -->
</html>

dayzoffer/templates/category_menu.html
{% load mptt_tags %}
{% load custom_tags %}
{% load staticfiles %}
<style type="text/css">


.description {
    position: absolute;
    top: 50%;
    left: 50%;
    -webkit-transform: translateY(-50%);
    -ms-transform: translateY(-50%);
    transform: translateY(-50%);
    -webkit-transform: translateX(-50%);
    -ms-transform: translateX(-50%);
    transform: translateX(-50%);
}



.menu-container {
    width: 100%;
    margin: 0 auto;

    background: rgb(0, 108, 180);
}

.menu-mobile {
    display: none;
    padding: 20px;
}

.menu-mobile:after {
    content: "\f00b";
    font-family: FontAwesome;
    font-size: 2.5rem;
    padding: 0;
    float: right;
    position: relative;
    top: 50%;
    -webkit-transform: translateY(-25%);
    -ms-transform: translateY(-25%);
    transform: translateY(-25%);
}

.menu-dropdown-icon:before {
    content: "\f13a";
    font-family: FontAwesome;
    display: none;
    cursor: pointer;
    float: right;
    padding: 1.5em 2em;
    background: #fff;
    color: #333;
}

.menu > ul {
    margin: 0 auto;
    width: 100%;
    list-style: none;
    padding: 0;
    position: relative;
   
    box-sizing: border-box;

}

.menu > ul:before,
.menu > ul:after {
    content: "";
    display: table;
}

.menu > ul:after {
    clear: both;
}

.menu > ul > li {
    float: left;
    background: rgb(0, 108, 180);
    padding: 0;
    margin: 0;

}

.menu > ul > li a {
    text-decoration: none;
    padding: 1em 1em;
    display: block;
    color:white;
}

.menu > ul > li:hover a {
    color:black;
}

.menu > ul > li:hover {
    background: #f0f0f0;
    border-top-left-radius:5px;
    border-top-right-radius:5px;
}

.menu > ul > li > ul {
    display: none;
    width: 100%;
    background: #f0f0f0;
    padding: 20px;
    position: absolute;
    z-index: 99;
    left: 0;
    margin: 0;
    list-style: none;
    box-sizing: border-box;
    border-bottom-left-radius: 5px;
    border-bottom-right-radius: 5px;
}

.menu > ul > li > ul:before,
.menu > ul > li > ul:after {
    content: "";
    display: table;
}

.menu > ul > li > ul:after {
    clear: both;
}

.menu > ul > li > ul > li {
    margin: 0;
    padding-bottom: 0;
    list-style: none;
    width: 25%;
    background: none;
    float: left;
}

.menu > ul > li > ul > li a {
    color: #777;
    padding: .2em 0;
    width: 95%;
    display: block;
    border-bottom: 1px solid #ccc;
}
.menu > ul > li > ul > li a:hover {
    border: 1px solid orange;
}

.menu > ul > li > ul > li > ul {
    display: block;
    padding: 0;
    margin: 10px 0 0;
    list-style: none;
    box-sizing: border-box;
}

.menu > ul > li > ul > li > ul:before,
.menu > ul > li > ul > li > ul:after {
    content: "";
    display: table;
}

.menu > ul > li > ul > li > ul:after {
    clear: both;
}

.menu > ul > li > ul > li > ul > li {
    float: left;
    width: 100%;
    padding: 10px 0;
    margin: 0;
    font-size: .8em;
}

.menu > ul > li > ul > li > ul > li a {
    border: 0;
}

.menu > ul > li > ul.normal-sub {
    width: 300px;
    left: auto;
    padding: 10px 20px;
}

.menu > ul > li > ul.normal-sub > li {
    width: 100%;
}

.menu > ul > li > ul.normal-sub > li a {
    border: 0;
    padding: 1em 0;
}


/* ––––––––––––––––––––––––––––––––––––––––––––––––––
Mobile style's
–––––––––––––––––––––––––––––––––––––––––––––––––– */

@media only screen and (max-width: 959px) {
    .menu-container {
        width: 100%;
    }
    .menu-mobile {
        display: block;
    }
    .menu-dropdown-icon:before {
        display: block;
    }
    .menu > ul {
        display: none;
    }
    .menu > ul > li {
        width: 100%;
        float: none;
        display: block;
    }
    .menu > ul > li a {
        padding: 1.5em;
        width: 100%;
        display: block;
    }
    .menu > ul > li > ul {
        position: relative;
    }
    .menu > ul > li > ul.normal-sub {
        width: 100%;
    }
    .menu > ul > li > ul > li {
        float: none;
        width: 100%;
        margin-top: 20px;
    }
    .menu > ul > li > ul > li:first-child {
        margin: 0;
    }
    .menu > ul > li > ul > li > ul {
        position: relative;
    }
    .menu > ul > li > ul > li > ul > li {
        float: none;
    }
    .menu .show-on-mobile {
        display: block;
    }
}
</style>


{% set_node as nodes %}

<div class="menu-container">
    <div class="container">
        <div class="menu">
            <ul>
				{% recursetree nodes %}
			   <li><a href="#">{{ node.name }}</a>
			   		{% if not node.is_leaf_node %}
			   		<ul>
			        	{{ children }}
				    </ul>
				    {% endif %}
			   </li>

			    {% endrecursetree %}
			</ul>
        </div>
    </div>
 </div>

dayzoffer/templates/footer.html
{% load staticfiles %}
{% load custom_tags %}
<div class="section footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-3 col-xs-12">
        <div class="logo-footer text-theme">
          <img src="{% static 'assets/images/logo/logo-footer-d.png' %}" height="80px" alt="theme-img">
        </div>
        <p class="text-theme">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet consectetur massa, in efficitur justo aliquam.</p>
        <div class="text-theme">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-facebook fa-round"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter fa-round"></i></a></li>
            <li><a href="#"><i class="fa fa-dribbble fa-round"></i></a></li>
            <li><a href="#"><i class="fa fa-linkedin fa-round"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-sm-offset-1 col-xs-6">
        <h3 class="text-theme title-sm hr-left">Menu</h3>
        {% set_node as nodes %}
        <ul class="list-unstyled text-theme">
        {% for node in nodes %}
        {% if node.is_root_node %}
          <li><a href="{% url 'offers:category-detail' node.slug %}">{{ node.name }}</a></li>
        {% endif %}
        {% endfor %}
        </ul>
      </div>
      <div class="col-sm-2 col-xs-6">
        <h3 class="text-theme title-sm hr-left">Pages</h3>
        <ul class="list-unstyled text-theme">
          <li><a href="about-us-option-1.html">About Us</a></li>
          <li><a href="services-option-2.html">Services</a></li>
          <li><a href="pricetables.html">Pricing Tables</a></li>
          <li><a href="contact-us-option-1.html">Contact</a></li>
          <li><a href="coming-soon-option-1.html">Coming Soon</a></li>
          <li><a href="faq.html">FAQs</a></li>
        </ul>
      </div>
      <div class="col-sm-4 col-xs-12">
        <h3 class="text-theme title-sm hr-left">Subscribe To Our Newsletter</h3>
        <br/>
        <form action="{% url 'newsletter' %}" method="post">{% csrf_token %}
        <div class="input-group text-theme">

          <input type="text" class="form-control input-lg" name="news-email" placeholder="E-mail">
          <span class="input-group-btn">
            <button type="submit" class="btn btn-pink input-lg btn-z-index"><i class="fa fa-paper-plane"></i>Subscribe</button>
          </span>
        </div>
        </form>
      </div>
    </div>
  </div>
</div>
<!--SECTION FOOTER BOTTOM -->
<!--===============================================================-->
<div class="section footer-bottom">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center col-footer-bottom">
        <a id="scroll-top" href="#"><i class="fa fa-angle-up fa-2x"></i></a>
        <p class="copyright">2015 &copy; Z-Theme. All Rights Reserved.</p>
      </div>
    </div>
  </div>
</div>

dayzoffer/templates/head_css.html
 {% load staticfiles %}
 <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">

  <link rel="stylesheet" href="{% static 'css/custom.css' %}">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

dayzoffer/templates/header.html
{% load mptt_tags %}
{% load custom_tags %}
{% load staticfiles %}
<div id="header">
  <nav id="nav" class="navbar navbar-default navbar-fixed-top">
    <div class="menu-top menu-top-inverse">
      <div class="container">
        <div class="row">
          <div class="col-sm-5 col-xs-12">
              <form class="form-inline">
                <div class="form-group col-xs-6">
                {% set_city as cities %}
                  <select style="width:100%;" id="citySearch" class="form-control select input-sm">
                    <option>--Select City--</option>
                  {% for city in cities %}
                    <option>{{ city }}</option>
                  {% endfor %}
                  </select>
                </div>
                <div class="form-group col-xs-6">
                  <select style="width:100%;" class="form-control input-sm">
                    <option>--Select Area--</option>
                    <option>Select</option>
                    <option>Select</option>
                  </select>
                </div>
              </form>
          </div>
          <div class="col-sm-7 col-xs-12">
            <div class="pull-right">
            {% if request.user.is_authenticated %}
              <div class="pull-left">
                <h5 style="color: white;">Hi {{request.user.username }}!</h5>
              </div>
              <div class="pull-left">
                <a href="{% url 'accounts:logout' %}"><button class="btn-menu-top" id="dLabel" type="button">Logout</button></a>
              </div>
            {% else %}
              <div class="pull-left">
                <a href="{% url 'accounts:signin' %}"><button class="btn-menu-top" id="dLabel" type="button"><i class="fa fa-user"></i> Log in</button></a>
              </div>
              <div class="pull-left">
                <a href="{% url 'accounts:register' %}"><button class="btn-menu-top hidden-xs" id="dShop" type="button"><i class="fa fa-user"></i> Register</button></a>
              </div>
              <div class="pull-left">
                <a class="btn-menu-top" id="dShop" href="{% url 'accounts:vendor_login' %}"><i class="fa fa-users"></i> Shopkeeper</a>
              </div>
            </div>
            <div class="list-inline social-icons-menu-top pull-right">
              <a href="#" class="social-hover-v1 a-facebook"></a>
              <a href="#" class="social-hover-v1 a-google"></a>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><img class="img-responsive" width="236px" src="{% static 'assets/images/logo/logo-default-d.png' %}" alt="theme-img"></a>
      </div>
{% set_node as nodes %}  
      <div id="navbar" class="navbar-collapse collapse">

        <ul class="nav navbar-nav navbar-right">
          {% recursetree nodes %}
           <li class="dropdown"><a href="{% url 'offers:category-detail' node.slug %}">{{ node.name }}</a>
              {% if not node.is_leaf_node %}
              <ul class="dropdown-menu dropdown-menu-left">
                  {{ children }}
              </ul>
              {% endif %}
           </li>

          {% endrecursetree %}
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>
</div>

dayzoffer/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="section-intro-index section-slider">
  <div class="layer-intro layer-intro-index">
    <!-- SLIDER -->
    <div class="wrapper-slider" id="intro-slider-wrapper">
      <div class="carousel slide carousel-intro" id="carousel-intro" data-ride="carousel" data-interval="7500">
        <div class="wrapper-preloader">
          <div id="preloader"></div>
        </div>
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#carousel-intro" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-intro" data-slide-to="1"></li>
          <li data-target="#carousel-intro" data-slide-to="2"></li>
        </ol>
        <!-- Wrapper for slides -->
        <div class="carousel-inner">
        {% if home_slider %}
        {% for slider in home_slider %}

        {% if home_slider.first == slider %}
          <!-- first slide -->
          <div class="item item-theme-first active">
            <div class="container">
              <div class="row">
                <div class="col-sm-7">
                  <h1 class="text-theme title-xl mt-40 animation an-delay-05 an-duration-04 fadeInLeftSlider">{{ slider.caption1 }}</h1>
                  <p class="text-theme lead animation an-delay-09 an-duration-04 fadeInUpSlider">{{ slider.caption2 }}</p>
                </div>
                <div class="col-sm-5 hidden-xs">
                  <img class="pull-right animation an-delay-19 an-duration-04 fadeInUpSlider" src="{{ slider.image.url }}" alt="theme-img">
                </div>
              </div>
            </div>
          </div>
        {% else %}
          <div class="item item-theme">
            <div class="container">
              <div class="row">
                <div class="col-sm-6">
                  <h1 class="text-theme title-xl mt-40 animation an-delay-05 an-duration-04 fadeInUpSlider">{{ slider.caption1 }}</h1>
                  <p class="text-theme lead animation an-delay-07 an-duration-04 fadeInRightSlider">{{ slider.caption2 }}</p>
                </div>
                <div class="col-sm-5 col-sm-offset-1 hidden-xs">
                  <img class="img-responsive img-slide-2 pull-right mt-20 animation an-delay-18 an-duration-04 fadeInUpSlider" src="{{ slider.image.url }}" alt="theme-img">
                </div>
              </div>
            </div>
          </div> 
        {% endif %}
        {% endfor %}
        {% endif %}
        </div>
      </div>
    </div>
    <!-- SLIDER END-->
  </div>
  <!-- Controls -->
  <a href="#carousel-intro" role="button" data-slide="prev">
    <i class="fa fa-angle-left fa-2x btn-prev-intro"></i>
  </a>
  <a href="#carousel-intro" role="button" data-slide="next">
    <i class="fa fa-angle-right fa-2x btn-next-intro"></i>
  </a>
</div>

<!-- SECTION CALL-TO -->
<!--===============================================================-->
<div class="section section-both section-primary section-arrow-bottom section-xs inset-shadow-top">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <h3 class="title-md text-theme">BEST OFFERS ARE WAITING FOR YOU</h3>
      </div>
    </div>
  </div>
</div>

<!-- Multiple Slides -->
<!--===============================================================-->
{% if best_offer %}
<div class="section section-sm section-both section-shop-items">
  <div class="container">
    <div id="owl-portfolio-item" class="owl-carousel">
    {% for offer in best_offer %}
      <div class="item">
        <a href="{{ offer.get_absolute_url }}" class=""><img class="img-responsive" src="{{ offer.image.url }}" alt="portfolio" style="height: 200px;">
        </a>
        <div class="caption-portfolio">
          <h3 class="text-theme title-xs">{{ offer.name }}</h3>
          <p class="text-theme">{{ offer.description }}</p>
        </div>
      </div>
    {% endfor %}
    </div>    
  </div>
</div>
{% endif %}
<!-- SECTION -->
<!--===============================================================-->
<div class="section section-sm section-both section-shop-items">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 class="title-md hr-left text-uppercase">Latest Offers</h1>
      </div>
    </div>
    <div class="row mt-20">
    {% for offer in latest_offers %}
      <div class="col-sm-3">
        <div class="shop-box bordered">
          <a href="{{ offer.get_absolute_url }}" class="img-box text-theme">
            <img class="img-responsive" src="{{ offer.image.url }}" alt="img-theme" style="height: 200px;">
          </a>
          <h3 class="title-sm text-theme text-theme-sm"><a href="{{ offer.get_absolute_url }}">{{ offer.name }}</a></h3>
          <p class="text-theme-sm"><small>{{ offer.description }}</small>
          </p>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
</div>
{% endblock content %}

dayzoffer/templates/navbar.html
{% load staticfiles %}
<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-c">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav top-nav navbar-right">
            <li><a href="#">Home</a></li>
            {% if request.user.is_authenticated %}
            <li><a href="#about">Hi! {{ request.user.first_name }} </a></li>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'accounts:signin' %}">Sign In</a></li>
            <li><a href="{% url 'accounts:register' %}">Register</a></li>
            {% endif %}
            <li><a href="{% url 'accounts:seller-register' %}">Seller Register</a></li>
            <li><a href="{% url 'accounts:vendor_login' %}">Seller Login</a></li>
          </ul>
          <ul class="nav navbar-nav top-nav">
            <li><a href="../navbar/"><i style="color: blue;font-size: 21px;" class="fa fa-facebook-square"></i></a></li>
            <li><a href="../navbar/">Twitter</a></li>
          </ul>
        </div>
      </div>
    </nav>
    
 

dayzoffer/templates/search_result.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="section section-sm section-both section-shop-items">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 class="title-md hr-left text-uppercase">Latest Offers</h1>
      </div>
    </div>
    <div class="row mt-20">
    {% for offer in latest_offers %}
      <div class="col-sm-3">
        <div class="shop-box bordered">
          <a href="{{ offer.get_absolute_url }}" class="img-box text-theme">
            <img class="img-responsive" src="{{ offer.image.url }}" alt="img-theme" style="height: 200px;">
          </a>
          <h3 class="title-sm text-theme text-theme-sm"><a href="{{ offer.get_absolute_url }}">{{ offer.name }}</a></h3>
          <p class="text-theme-sm"><small>{{ offer.description }}</small>
          </p>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
</div>
{% endblock content %}